# Generated by Django 5.2.8 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tour_app', '0012_add_ngome_kongwe_zanzibar_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=30)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('car', 'Private car'), ('van', 'Private van'), ('suv', 'SUV / 4x4')], default='car', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ('-created_at',)},
        ),
    ]
